### ISSUE TITLE
Threshold directionality

### ISSUE THREAD

**Issue by adamhadani** [shaharke/influx-nagios-plugin#1]
Is there a way to specify which side of the threshold an 'OK' value is?
e.g for something like tracking free memory, I would like to have warning if value is _below_ the warning threshold alert value, for something like cpu iowait i would like to have an alert if value is _above_ the threshold, etc.

**Comment by adamhadani** [comment]
nm, I assume can just use start nagios syntax e.g '-w 10:' etc?

**Comment by shaharke** [comment]
That's correct. See the following resources:
https://nagios-plugins.org/doc/guidelines.html
https://pythonhosted.org/NagAconda/plugin.html#api-specification

**Comment by shaharke** [comment]
@adamhadani Let me know if that worked for you

**Comment by adamhadani** [comment]
@shaharke yep works great, thanks Shahar
