### ISSUE TITLE
Need some help with syntax

### ISSUE THREAD

**Issue by cjs226span** [shaharke/influx-nagios-plugin#2]
I'm able to query using curl:

> curl -G 'http://localhost:8086/db/metrics/series?u=root&p=root' --data-urlencode "q=select CALENDAR from /system.bg-www-s.bg-www-s-01.app.scar.backupcli.enqueue.finished/ limit 1"
> [{"name":"system.bg-www-s.bg-www-s-01.app.scar.backupcli.enqueue.finished","columns":["time","sequence_number","CALENDAR"],"points":[[1428199939816,800001,173]]}]

However, I fail when trying to use the plugin:

> /usr/local/bin/check_influx -h localhost:8086 -u root -p root -d metrics -q "select CALENDAR from /system.bg-www-s.bg-www-s-01.app.scar.backupcli.enqueue.finished/" -w 1 -c 2
> Status Unknown: Failed to query InfluxDB: 404: 404 page not found

**Comment by shaharke** [comment]
Does this happen with all metrics or only with this one? Are you familiar with Python? If you are, I would be happy if you could use the InfluxDB client directly and see if you get the same error message.

**Comment by cjs226span** [comment]
I'm seeing it with all metrics I've tried thus far.

I'm able to retrieve data using the python influxDB client:

> > > from influxdb.influxdb08 import InfluxDBClient
> > > client = InfluxDBClient('localhost', 8086, 'root', 'root', 'metrics')
> > > result = client.query('select CALENDAR from /system.bg-www-s.bg-www-s-01.app.scar.backupcli.enqueue.finished/')
> > > print("Result: {0}".format(result))
> > > Result: [{u'points': [[1428199939, 800001, 173]], u'name': u'system.bg-www-s.bg-www-s-01.app.scar.backupcli.enqueue.finished', u'columns': [u'time', u'sequence_number', u'CALENDAR']}]

**Comment by cjs226span** [comment]
Figured it out.  I'm still running 0.8.8 so I had to change the following line:

from influxdb import client as influxdb

to:

from influxdb.influxdb08 import client as influxdb
